import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "@openzeppelin/contracts/token/ERC721.sol"
import "@openzeppelin/contracts/access/Ownable.sol";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nft store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>nft store</h1>
    </div>
  )
}
